name = "AlertPushover"
uuid = "19f6540d-ecb3-4e88-b99d-153996aa3b9b"
authors = ["David Little <david.frank.little@gmail.com> and contributors"]
version = "0.1.1"

[deps]
Alert = "28312eec-4d86-447d-83ad-bc2b262de792"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"

[compat]
Alert = "0.2"
HTTP = "0.8, 0.9"
julia = "1"
